# Generated by Django 3.2.4 on 2021-07-04 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_examplemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleModel',
            new_name='Markdown',
        ),
    ]
