# Generated by Django 3.2.4 on 2021-07-04 04:51

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_rename_examplemodel_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
    ]
