# Generated by Django 3.2.4 on 2021-11-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='static/assets/img/post-bg.jpg', upload_to='images/'),
        ),
    ]
